service: image-resize

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-south-1
  apiKeys:
    - ${env:MY_API_KEY}
  usagePlan:
    quota:
      limit: 50 #The maximum number of requests that can be made in a given time period.
      offset: 2 #The number of requests subtracted from the given limit in the initial time period.
      period: MONTH #The time period in which the limit applies. Valid values are "DAY", "WEEK" or "MONTH".
    throttle:
      burstLimit: 10 #The maximum API request rate limit over a time ranging from one to a few seconds. The maximum API request rate limit depends on whether the underlying token bucket is at its full capacity. 
      rateLimit: 10 #The API request steady-state rate limit (average requests per second over an extended period of time)


functions:
  imageResize:
    handler: handler.imageResize

    events:
      - http:
          path: image/resize
          method: get
          cors: true
          private: true

